version: "3.2"

services:
    php: 
      volumes:
          - ./:/var/www/html
      image: php:8.0-apache
      container_name: php8_container
      restart: always
      ports:
          - "80:80"
          - "443:443"
      links:
          - db
          - mysql
          - phpmyadmin
          - mongo-express

    db:
      image: mongo:4.2
      container_name: mongodb_container
      restart: always
      ports:
         - "27017:27017"
      environment:    
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: admin

    mongo-express:
      image: mongo-express:0.54.0
      restart: always
      container_name: mongo-express_container
      ports:
        - 8080:8081
      environment:
        ME CONFIG MONGODB ADMINUSERNAME: root
        ME CONFIG MONGODB ADMINPASSWORD: admin
        ME CONFIG MONGODB SERVER: db

    mysql:
      image: mysql:latest
      container_name: mysql_container
      restart: always
      volumes:
        - /var/lib/mysql
      ports:
        - 3306:3306
      environment:    
        - MYSQL_DATABASE=bd
        - MYSQL_ROOT_USER=root
        - MYSQL_ROOT_PASSWORD=root
        
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: phpmyadmin_container
      restart: always
      links:
        - db
      ports:
        - 88:80
      environment:
        - PMA_ARBITRARY=1

